### ISSUE TITLE
Null Function Pointer in Emitter since optimization

### ISSUE THREAD

**Issue by Jacic** [HaxePunk/HaxePunk#439]
- **HaxePunk version:** git, as of ["Emitter optimization."](https://github.com/HaxePunk/HaxePunk/commit/6aca5ec8cfe6f624c4e8aed0653c0508846de9f9)
- **Target(s):** Tested on Linux
- **Haxe version:** Tested on 3.2.1
- **OpenFL/Lime or NME version:** Any, including latest: OpenFL 4.7.0, Lime 3.7.0

Stacktrace:
```
Called from haxepunk.Engine::onEnterFrame haxepunk/Engine.hx line 325
Called from haxepunk.Engine::render haxepunk/Engine.hx line 165
Called from haxepunk.Scene::render haxepunk/Scene.hx line 170
Called from haxepunk.Entity::render haxepunk/Entity.hx line 180
Called from haxepunk.graphics.Emitter::renderAtlas haxepunk/graphics/Emitter.hx line 206
Called from haxepunk.graphics.Emitter::renderParticles haxepunk/graphics/Emitter.hx line 170
Error : Null Function Pointer
```

**Comment by bendmorris** [comment]
I believe this was already fixed in the dev branch - can you confirm?

**Comment by Jacic** [comment]
I've been testing the dev branch. I just pulled the latest version of the Emitter.hx file, as of [Move fixed timestep logic](https://github.com/HaxePunk/HaxePunk/commit/1e4db8c9045fa9fb995b5728e140840bfb665221). I'm still getting the crash.

**Comment by bendmorris** [comment]
You're right, I missed one. Hopefully should be fixed as of https://github.com/HaxePunk/HaxePunk/commit/b7db849a9ca272913b357734ecfdc0ee0fdcd156

**Comment by Jacic** [comment]
Yep, that did it.
